version: "3.8"

services:
  demo_backend:
    container_name: demo-backend
    build:
      dockerfile: Dockerfile
      context: backend
    environment:
      - GUNICORN_CMD_ARGS=--reload
      - MONGO_URI=mongodb://root:password@demo_db:27017
    volumes:
      - "./backend/src:/app/src"
    ports:
      - "5001:5001"
  demo_frontend:
    container_name: demo-frontend
    build:
      dockerfile: Dockerfile
      context: frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
  demo_db:
    container_name: demo-db
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - demo_db_vol:/data/db
volumes:
  demo_db_vol:
